name: Release

on:
    push:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Run tests
              run: make test

    build:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Build and package the binary
              run: |
                  make build

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: ${{ runner.os }}-binary
                  path: nino

    git-tagging:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Generate version tag
              id: generate_tag
              run: |
                  version=$(date +"%Y.%m.%d.%H%M%S")
                  echo "tag=v$version" >> $GITHUB_ENV

            - name: Create Git Tag
              uses: EndBug/create-tag-action@v1
              with:
                  tag: ${{ env.tag }}
                  message: "Release version ${{ env.tag }}"
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    release:
        needs: git-tagging
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Download artifact
              uses: actions/download-artifact@v4
              with:
                  name: ${{ runner.os }}-binary

            - name: Generate release notes
              id: generate_notes
              run: |
                  notes="Changes in this Release:\n"
                  notes+=$(git log -1 --pretty=format:"%s")
                  echo "body=$notes" >> $GITHUB_ENV

            - name: Create release
              id: create_release
              uses: actions/create-release@v1.1.0
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Provided by Actions
              with:
                  tag_name: "${{ env.tag }}"
                  release_name: "Release ${{ env.tag }}"
                  body: "${{ env.body }}"
                  draft: false
                  prerelease: false
